### ISSUE TITLE
[ROADMAP] 라이브러리 리팩토링 로드맵

### ISSUE THREAD

**Issue by kms0219kms** [Team-IF/comcigan-py#18]
현재 컴시간에서 계속 구조변경을 하고있고, 2학기를 맞아 또 다시 자잘한 구조 변경으로 서비스 운영을 어렵게 할 것으로 예상되어, 메인테이너로서 이 부분에 대해서 대응할 수 있는 방안을 모색해보려고 합니다.

1. 현재 작동하는 방식
현재는 레거시에 레거시 위에 어찌어찌 픽스 패치들에 의존에 겨우 돌아가는 상황으로 조금의 구조 변경에도 취약합니다.

2. 앞으로 어떻게 대응할 것인가
전체 리라이트는 좀 그렇더라도, 단순히 일단 작동만 하면 끝 이 아니라, 최대한 새로 어떻게 구조가 바뀌었고, 어떻게 해야 안정적일지 고민해보고 그 방법대로 픽스를 배포하려고 합니다.

마침 일부 다른언어 구현체 개발해 주시는 분들깨서 이를 documentation 화 해서 공개해 주신 곳들도 있어서, 같이 참고하며 개선해 나가고자 합니다.

3. 여담
현재 이 레포 소유주 분도 그렇고, 저도 그렇고 컴시간을 만질일이 자주 없었습니다. 바쁘기도 했고요. 그래서 조금 관리에 소홀한 부분이 없지않아 있었습니다만, 조만간 남아있는 문제들 해결하고 본격적으로 관리를 다시 시작해 보도록 하겠습니다. 감사합니다!

**Comment by Coder-Iro** [comment]
이번에 리팩토링을 하게 되면 들어가야 될 기능은

- [ ] 학교 + 지역 검색
- [ ] 학교 이름 search 가 아닌 exact match
- [ ] sccode 수동 지정
- [ ] 금주 + 차주 시간표 지원
- [ ] 변경 여부 (컴시간 기준 노란 음영) 확인

정도가 있지 않으려나 싶네요...

다운로드 수가 그래도 꽤 나오는데 오랫동안 방치해둔 것에 대해서는 책임을 깊이 통감하고 있으나.. 제대로 개발에 손을 대기 위해서는 이번년도 수능이 끝나야 하는지라 사용자 분들께 죄송할 따름입니다...

**Comment by kms0219kms** [comment]
sccode 수동 지정은 제대로 컴시간에서 지원 자체를 안해서... 조금 더 들여다봐야하는 부분입니다.
Ref)
![image](https://github.com/user-attachments/assets/9fcc9f86-19e7-45da-a565-4a18f3134fb2)

**Comment by kms0219kms** [comment]
@Coder-Iro 본 리팩토링은 refactor/kms0219kms 에서 제가 작업해 보고 있겠습니다! 중간중간 리뷰만 해주시면 될거같아요

아니면 아예 제 인생 최초로 TDD를 해보아도 될 거 같습니다 ㅋㅎ
